### PR TITLE
make TreeBreakListener.processTreeBlockBreak public, callable from other plugins

### PR DESCRIPTION
**Pull request by benjajaja**
Hi, I wanted to let my plugin use yours (because it's awesome!) instead of copypasting your code.

### CODE REVIEW

**Comment by betterphp** [comment]
I don't see the harm i this :)

**Comment by betterphp** [comment]
Although, are you looking for a method to get the tree blocks ?

**Comment by benjajaja** [comment]
No, only to let your plugin also decay trees that weren't destroyed by a player. My plugin will remove some tree-logs, and should call yours to do the rest.
Maybe a hook to instantly process the decay (only for a specific tree) would be useful, but I'm not sure how much change to your plugin that would mean.

**Comment by betterphp** [comment]
Hmm, I don't think that would be simple to add :s I'll have a think about it ;)

**Comment by benjajaja** [comment]
Yeah don't worry :) If I absolutely need I'll give it a try.

**Comment by betterphp** [comment]
How about changing the method you made public into one that gets the tree blocks (if it's a tree), then you can set them all to air yourself with only a few lines. I'd be fine with make that change if it makes your life easier ;)

**Pull request merged**
